name: Tests

on:
  - pull_request
  - push

env:
  CI: 1

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - run: npm install
      - run: npm run test:full
